# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle 8.1.1
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.1.1"
    - name: Build with Gradle 8.1.1
      run: ./gradlew build
    - name: Upload a Spigot plugin
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-spigot.jar
        path: spigot/build/libs/DiscordChat-spigot-*.jar
    - name: Upload a Forge1.12.2 mod
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-forge1.12.2.jar
        path: forge12/build/libs/DiscordChat-forge*.jar
    - name: Upload a Forge1.16.5 mod
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-forge1.16.5.jar
        path: forge16/build/libs/DiscordChat-forge*.jar
    - name: Upload a Forge1.19.2 mod
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-forge1.19.2.jar
        path: forge19/build/libs/DiscordChat-forge*.jar
    - name: Upload a Fabric1.18.2 mod
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-fabric1.18.2.jar
        path: fabric18/build/libs/DiscordChat-fabric*.jar
    - name: Upload a Forge1.20.1 mod
      uses: actions/upload-artifact@v4
      with:
        name: DiscordChat-forge1.20.1.jar
        path: forge20/build/libs/DiscordChat-forge*.jar
